### ISSUE TITLE
Using GC2145 on Arduino GIGA

### ISSUE THREAD

**Issue by cyhcyhgo** [openmv/openmv#2193] opened 2024-04-13 09:10 UTC
Hello! I flashed v4.5.3 firmware on my Arduino GIGA board since this version supports GC2145. But when I plug in GC2145 module(bought from ArduCam), the IDE cannot detect the camera. Does there still have problem on drivering GC2145? 
![image](https://github.com/openmv/openmv/assets/80203701/fb9ee0e9-d3e3-4504-bfd8-2c52c972a961)
![IMG_20240413_165135](https://github.com/openmv/openmv/assets/80203701/09c7db44-25ae-494a-adaa-38cbd2e228a3)

**Comment by cyhcyhgo** [comment] 2024-04-13 09:15
"无"means "None of sensors have been detected."

**Comment by kwagyeman** [comment] 2024-04-13 16:09
Hi, the sensor support is not enabled by default. You'd need to enable it in our firmware. Arduino isn't selling that camera module on their store so it's not on in our firmware.

**Comment by cyhcyhgo** [comment] 2024-04-13 16:18
> Hi, the sensor support is not enabled by default. You'd need to enable it in our firmware. Arduino isn't selling that camera module on their store so it's not on in our firmware.

Thanks for your reply. Referring from "omv_boardconfig.h", it seems like the GC2145 is supported in Arduino GIGA. Shall I add extra code to enable it?
![image](https://github.com/openmv/openmv/assets/80203701/eedc5edc-e91a-4204-89fe-b4efbc36c467)

**Comment by kwagyeman** [comment] 2024-04-13 16:22
Yeah, you just need to turn that 0 to 1 and then recompile and load the new firmware.

**Comment by kwagyeman** [comment] 2024-04-13 16:22
Oh! It's already enabled.

Mmm.

**Comment by cyhcyhgo** [comment] 2024-04-13 16:26
> Oh! It's already enabled.
> 
> Mmm.
> 
> The OV5640 being enabled may conflict with it. Try turning that camera off in the config file.

Thanks very much. I'll try it later. But why does OV5640 conflict with GC2145?

**Comment by kwagyeman** [comment] 2024-04-13 17:02
I think they have the same I2C address. Ibrahim added some code though to handle this and figure out which one is attached when this is the case.

I'll have to check what's happening exactly later and I can provide an update.

**Comment by kwagyeman** [comment] 2024-04-14 02:06
Yeah, Ibrahim already added code to fix this issue. It should work.

@iabdalkader - Any thoughts?

**Comment by cyhcyhgo** [comment] 2024-04-15 04:32
> Yeah, Ibrahim already added code to fix this issue. It should work.


Thanks for your work. But I flashed the latest development firmware(4.5.4), the problem still exist.

**Comment by iabdalkader** [comment] 2024-04-15 07:51
Yes this issue has been fixed and someone else tested it and confirmed it was fixed. I have a Giga for testing and some OV7x modules, but I don't have that external GC2145 module to test it myself.

I did try the same sensor config with the Nicla Vision (which has an on-board GC2145) and it detects it with the OV5640 enabled:

```
// Image sensor drivers configuration.
#define OMV_OV5640_ENABLE                   (1)
#define OMV_OV5640_AF_ENABLE                (1)
#define OMV_OV5640_PLL_CTRL2                (0x90)
#define OMV_OV5640_PLL_CTRL3                (0x13)
#define OMV_OV5640_XCLK_FREQ                (12000000)

#define OMV_OV7670_ENABLE                   (1)
#define OMV_OV7670_VERSION                  (75)
#define OMV_OV7670_CLKRC                    (0)

#define OMV_GC2145_ENABLE                   (1)
```

Whatever is wrong with your board must be a different issue.

**Comment by cyhcyhgo** [comment] 2024-04-15 08:19
> Whatever is wrong with your board must be a different issue.

Yes, the Nicla Vision could detect another sensor, but GIGA could not detect any sensor.

**Comment by kwagyeman** [comment] 2024-04-17 04:26
Closing this since it's not an issue with our software it seems.

**Closed by kwagyeman** 2024-04-17 04:26 UTC
