### ISSUE TITLE
PX4 Cant recognize Mavlink Optical Flow example.

### ISSUE THREAD

**Issue by tech0x** [openmv/openmv#558] opened 2019-07-27 14:22 UTC
### Steps to reproduce
1. Upload mavlink example to OpenMV H7 board.
2. Check correct output data, with mavproxy.
3. Connect to serial port Pixhawk 4.2.8, with PX4 1.9.2 firmware.
4. run Mavlink Inspector in QGroundControl and nothing to see, no optical flow messages at all.

I cant receive any optflow messages in QGroundControl.

**Comment by tech0x** [comment] 2019-07-28 03:48
I made some debug work and find these:
1. PX4 handle only OPTICAL_FLOW_RAD via mavlink MSGID 106 instead OPTICAL_FLOW MSGID 00.
2. But structure OPTICAL_FLOW_RAD to different.
OPTICAL_FLOW_RAD:
uint32_t integration_time_us; /*< [us] Integration time. Divide integrated_x and integrated_y by the integration time to obtain average flow. The integration time also indicates the.*/
float integrated_x; /*< [rad] Flow around X axis (Sensor RH rotation about the X axis induces a positive flow. Sensor linear motion along the positive Y axis induces a negative flow.)*/
float integrated_y; /*< [rad] Flow around Y axis (Sensor RH rotation about the Y axis induces a positive flow. Sensor linear motion along the positive X axis induces a positive flow.)*/
float integrated_xgyro; /*< [rad] RH rotation around X axis*/
float integrated_ygyro; /*< [rad] RH rotation around Y axis*/
float integrated_zgyro; /*< [rad] RH rotation around Z axis*/
uint32_t time_delta_distance_us; /*< [us] Time since the distance was sampled.*/
int16_t temperature; /*< [cdegC] Temperature*/

OPTICAL_FLOW:
float flow_comp_m_x; /*< [m] Flow in x-sensor direction, angular-speed compensated*/
float flow_comp_m_y; /*< [m] Flow in y-sensor direction, angular-speed compensated*/
int16_t flow_x; /*< [dpix] Flow in x-sensor direction*/
int16_t flow_y; /*< [dpix] Flow in y-sensor direction*/
float flow_rate_x; /*< [rad/s] Flow rate about X axis*/
float flow_rate_y; /*< [rad/s] Flow rate about Y axis*/

How I can correctly translate values to OPTICAL_FLOW_RAD format ?

**Comment by coolsyn** [comment] 2019-09-01 06:52
when I ran AprilTag landing script in openmv H7, QGroundControl can not receive msg id = 149, but it can get message id =132, which confused me.

**Comment by iabdalkader** [comment] 2019-09-06 20:17
@kwagyeman

**Comment by kwagyeman** [comment] 2019-09-06 20:18
I don't really know what the problem is. Please ask Randy Mackaday.

**Comment by iabdalkader** [comment] 2019-09-08 20:15
@rmackay9 Can you help with this issue ?

**Comment by rmackay9** [comment] 2019-09-08 23:39
@iabdalkader, I'm afraid not.  PX4 is completely different software.  ArduPilot is the firmware that I used.

[ArduPilot's OpenMV for optical flow wiki page is here](http://ardupilot.org/copter/docs/common-openmv-optflow.html) which includes setup info for the camera.  [AP's precision landing page is here ](http://ardupilot.org/copter/docs/precision-landing-with-irlock.html)although it doesn't include OpenMV information the more general setup info is there.

I think that it's probably best to close this issue because it's not really an openmv issue.

**Comment by kwagyeman** [comment] 2019-09-08 23:45
Thanks!

**Closed by kwagyeman** 2019-09-08 23:45 UTC
