### ISSUE TITLE
GC2145 image at VGA resolution has washed out colors

### ISSUE THREAD

**Issue by sebromero** [openmv/openmv#1570] opened 2022-03-03 13:47 UTC
**Describe the bug**
The camera image shows incorrect colors at VGA resolution. The assumption is that there is something wrong with Bayer to RGB. Could be due to bad bayer sensor registers

**To Reproduce**
Set the resolution to VGA with `sensor.set_framesize(sensor.VGA)`
Take a snapshop with `img = sensor.snapshot() `

**Expected behavior**
The colors in the image should look the same as with QVGA resolution.

**Screenshots**
![image](https://user-images.githubusercontent.com/1326220/156557231-c959a3ee-bbf0-4729-96cc-60a759a357b2.png)
![image](https://user-images.githubusercontent.com/1326220/156557209-d47c26ec-ed4b-4d39-839f-acc2baadc06d.png)

**Please complete the following information**
 - IDE version: 2.9
 - Firmware version: 4.2.3
 - Board: NiclaV
 - OS: MacOS

**Comment by kwagyeman** [comment] 2022-03-03 16:52
This is easy to fix. It's just the default bayer pattern setting being wrong. Ibrahim just needs to test the four different patterns we support and it should be fixed.

**Comment by iabdalkader** [comment] 2022-03-03 16:56
I tested them all, this seems to be the right pattern. The issue is this sensor doesn't support processed bayer, it's outputting a raw image (no de-noise, no awb, color correction etc...). I can't find any setting to change it.

**Closed** 2022-03-06 03:14 UTC
Labels: bug

**Comment by iabdalkader** [comment] 2022-03-06 03:27
Hey @sebromero  I found some issues with the window and bayer format, the image should look better now.
