### ISSUE TITLE
Robustify MQTT.py for Arduino Nicla Vision

### ISSUE THREAD

**Issue by shan716** [openmv/openmv#1892] opened 2023-07-05 16:15 UTC
**Describe the bug**
The current mqtt.py is not robust enough to work with sockets at the moment.

**To Reproduce**
1. Go to Arduino Nicla Vision examples -> mqtt.py
2. Connect to a secure connection (not test.mosquitto.org)

**Expected behavior**
Mqtt connection to specified server 

**Additional Info**
https://forums.openmv.io/t/issues-running-mqtt-with-nicla-vision/8478

**Please complete the following information**
 - IDE version: 4.0
 - Firmware version: 4.4.3
 - Board: Arduino Nicla Vision
 - OS: iOs/Linux

**Comment by iabdalkader** [comment] 2023-07-05 16:23
Hi, there's nothing wrong with the mqtt client, it's just that the default example doesn't enable SSL connection by default as I mentioned before, you just need to pass `ssl=True` and remove the port then it will use SSL, did you try that ? Also you can see all possible args here: https://github.com/openmv/openmv/blob/master/scripts/libraries/mqtt.py#L33

Also there's a more robust mqtt client (in the sense that it reconnect etc..) based on the same client, here, and this one has been tested and can for sure connect over SSL:

https://github.com/arduino/arduino-iot-cloud-py/blob/main/src/arduino_iot_cloud/umqtt.py

**Comment by shan716** [comment] 2023-07-05 16:26
Okay, thank you for the quick response. I just put in this new ticket since kwagyeman mentioned that he wanted to robustify the mqtt program sockets as a response to my initial question in the openmv forum, but we can close it if this is not an issue. Apologies for the misunderstanding!

**Comment by iabdalkader** [comment] 2023-07-05 16:37
> but we can close it if this is not an issue. Apologies for the misunderstanding!

No worries, no you can keep it open until it's tested. I posted mainly so @kwagyeman doesn't waste time on the current mqtt client (we don't need to robustify it, we can just switch to the one I linked above).

**Comment by iabdalkader** [comment] 2023-07-05 17:26
Can you try with the latest dev-release ? There has been some issues with WiFi you know. 


> For the umqtt library, I am trying to connect like this: `client = MQTTClient("openmv", "192.168.1.6", ssl_params=True)`

For umqtt library in Arduino's IoT cloud repo, you just need to use the SSL port (8883) it uses SSL by default. The `ssl_params` is for passing certificates, keys etc..

**Comment by shan716** [comment] 2023-07-05 18:53
Thank you for your help. I have updated to the latest dev-release (firmware 4.4.3), but still seem to get the same ECONNRESET error. 

The umqtt library is having a similar issue when I connect: `client = MQTTClient("openmv", "192.168.1.6", 8883, ssl_params={})`

Error:
```Traceback (most recent call last):
  File "<stdin>", line 31, in <module>
  File "umqtt.py", line 107, in connect
OSError: [Errno 104] ECONNRESET```

Which corresponds to: `a = self.sock.connect(addr)`

Both libraries work when connecting to `test.mosquitto.org`, so I suspect that this isn't a wifi connectivity issue. I have also included a 1 minute wait period to ensure connection to wifi gets established.

**Comment by iabdalkader** [comment] 2023-07-05 18:58
Can you post your full script ? will give it a try

**Comment by shan716** [comment] 2023-07-05 19:01
Okay, thank you. I just removed the network SSID and Key from the code, but the rest is the same.

```
# MQTT Example.
# This example shows how to use the MQTT library to publish to a topic.

import time, network
from umqtt import MQTTClient

SSID='' # Network SSID
KEY=''  # Network key

# Init wlan module and connect to network
print("Trying to connect.")

wlan = network.WLAN(network.STA_IF)
wlan.deinit()
wlan.active(True)
wlan.connect(SSID, KEY)

# We should have a valid IP now via DHCP
print("WiFi Connected ", wlan.ifconfig())

time.sleep(60)

client = MQTTClient("openmv", "192.168.1.6", 8883, ssl_params={})
client.connect()
print("mqtt connected")

while (True):
    client.publish("openmv/test", "Hello World!")
    time.sleep_ms(1000)
```

**Comment by iabdalkader** [comment] 2023-07-05 19:49
> client = MQTTClient("openmv", "192.168.1.6", 8883, ssl_params={})

Are you running your own MQTT server ? There might be an issue with it, I can't help you with that, but I did tested and could connect to `test.mosquitto.org` with SSL without any issues:

```
import time, network

SSID='' # Network SSID
KEY=''  # Network key

# Init wlan module and connect to network
print("Trying to connect.")

wlan = network.WLAN(network.STA_IF)
wlan.active(True)
wlan.connect(SSID, KEY)

while (not wlan.isconnected()):
    time.sleep_ms(100)

print("WiFi Connected ", wlan.ifconfig())
client = MQTTClient("openmv", "test.mosquitto.org", ssl=True)
client.connect()

print("mqtt connected")

while (True):
    client.publish("openmv/test", "Hello World!")
    time.sleep_ms(1000)
```

**Comment by shan716** [comment] 2023-07-05 20:40
Thank you. Does this mean both the mqtt and umqtt libraries are not able to connect to my own server? I have been able to connect to my server using mqtt through the Arduino IDE, so it seems to be working. The issue I have is that I can only connect to test.mosquitto.org and not any personal servers while running mqtt in OpenMV.

**Comment by iabdalkader** [comment] 2023-07-05 20:44
> Does this mean both the mqtt and umqtt libraries are not able to connect to my own server?

No it means there might be something with the configuration of your server, that you need to figure out, it might be a disabled cipher, or different SSL version or something like that, I can't really help you with that as it's not my area of expertise, and I can't reproduce the issue, but wireshark might be helpful  if you can somehow capture the traffic from the nicla. As for Arduino libraries working, they use a different SSL library, which might also be configured differently.

**Comment by shan716** [comment] 2023-07-05 21:27
I see, I will try to figure it out, thank you for all your help!

**Comment by iabdalkader** [comment] 2023-07-10 16:38
A fix for this has been posted in issue https://github.com/openmv/openmv/issues/1871

**Closed by iabdalkader** 2023-07-10 16:38 UTC
