### ISSUE TITLE
Waking from pyb.standby() seems unreliable.

### ISSUE THREAD

**Issue by acutetech** [openmv/openmv#882] opened 2020-08-23 06:02 UTC
When running a fairly simple (but realistic) script using pyb.standby() to place OpenMV H7 in Standby state, and the RTC to wake it, I observe that sometimes the wake does not work. When running a script that should loop continuously, it will typically run a small number of times as expected, then stop with the camera is stuck drawing a relatively large current. The same script using pyb.stop() works correctly.

I prepared a script "simple_sleep.py" in a forum post "Low duty cycle to save power: examples?" which should allow the problem to be replicated: https://forums.openmv.io/viewtopic.php?f=6&t=1997&sid=519d03826cb81f2bcb02a622cfb9e1e0 The script is copiously documented.

One of three options can be chosen around line 152: don't sleep; use pyb.stop() to enter Sleep state then use the RTC to wake 10s later and resume; and use pyb.standby() to enter Standby state then use RTC to wake 10s later and reset the OpenMV camera. The pyb.stop() option works reliably. 

The code runs from onboard flash. Firmware is 3.6.7. The problem occurs with both M7 and H7 cameras. I am powering the boards through the USB connector from three AA cells in series, at about 4.4V. Of course the IDE is of no use in debugging.

**Comment by iabdalkader** [comment] 2020-08-23 17:15
> When running a script that should loop continuously, it will typically run a small number of times as expected, then stop with the camera is stuck drawing a relatively large current.

I can't reproduce this issue, but how can you run call standby in a loop ? The MCU is reset on exit from standby. Can you provide a smaller script that shows this issue ? just a few lines of code.

**Comment by acutetech** [comment] 2020-08-23 21:47
After I posted this bug report I posted a second (https://github.com/openmv/openmv/issues/883), relating to a crash when sensor.reset() was called if the OV7725 regulator had been switched off.

That gave me the idea to revisit this bug report, and see what would happen if I left the regulator on.
It turns out these are related: the crash reported here does NOT happen if I leave the OV7725 regulator on.

That is, at around line 154, this shows the bug:
    pause("standby", True)
but this does not:
    pause("standby", False)

where "True" executes this code before sleeping:
    sensor.__write_reg(0x4F, 0x18)

Note that _usually_ it does not matter if I shut down the regulator before calling pyb.standby() but _sometimes_ it does (and the crash reported here occurs).

It is not sufficient to say "so don't shut down the regulator then", as leaving the regulator on draws a LOT of current.

**Comment by iabdalkader** [comment] 2020-08-23 22:05
If you shut down the regulator there's no way to turn it back on without resetting the whole camera. Note sensor.reset() does Not toggle the reset GPIO, maybe it should it, instead it performs a soft-reset and re-writes the default registers, so it needs I2C working (the regulator on). Since standby resets the camera anyway, you should be able to shut-down the regulator, followed by standby just don't call any other sensor functions after shutting down the regulator.

**Comment by iabdalkader** [comment] 2020-08-27 16:26
I am closing this issue as it's basically the same issue as #883

**Closed by iabdalkader** 2020-08-27 16:26 UTC
